# Generated by Django 3.0.8 on 2020-10-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='s_id',
            field=models.IntegerField(default=1),
        ),
    ]
