# Generated by Django 3.0.8 on 2020-10-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_students_s_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default='test#gmail.com', max_length=30),
        ),
    ]
