# Generated by Django 3.0.8 on 2020-10-28 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_students_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Department'),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
    ]
