# Generated by Django 3.0.8 on 2020-10-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_students_s_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='d_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Department'),
        ),
        migrations.AddField(
            model_name='students',
            name='s_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='students',
            name='department_name',
            field=models.CharField(max_length=10),
        ),
    ]
