# Generated by Django 3.0.8 on 2020-10-28 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201028_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='d_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Department'),
        ),
    ]
