# Generated by Django 3.0.8 on 2020-10-28 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201028_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='department_name',
        ),
        migrations.AlterField(
            model_name='students',
            name='d_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Department', to='main.Department'),
        ),
    ]
