# Generated by Django 3.0.8 on 2020-10-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201028_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
