# Generated by Django 3.0.8 on 2020-10-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_students_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='pic',
        ),
        migrations.AlterField(
            model_name='students',
            name='s_id',
            field=models.CharField(max_length=10),
        ),
    ]
