# Generated by Django 3.0.8 on 2020-11-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201031_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='s_id',
            field=models.CharField(default='8956', max_length=10),
        ),
    ]
