# Generated by Django 3.0.8 on 2020-11-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201102_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='s_id',
            field=models.CharField(default='7620', max_length=10),
        ),
    ]
