# Generated by Django 3.0.8 on 2020-11-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201102_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='collage_id',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='students',
            name='s_id',
            field=models.CharField(default='3891', max_length=10),
        ),
    ]
