# Generated by Django 3.0.8 on 2020-11-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201102_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='s_id',
            field=models.CharField(default='5236', max_length=10),
        ),
    ]
